site_name: Rumor Detect Docs
repo_url: https://github.com/mikku39/rumor-detect.git
repo_name: rumor-detect
docs_dir: docs

nav:
  - Home: index.md
  - Tutorial: tutorial/tutorial.md
  - API Reference:
      - 主类: reference/rumor_detect.md
      - 关键字提取: reference/keyword.md
      - 新闻查找: reference/news.md
      - 文本概述: reference/summary.md
      - 文本对比: reference/compare.md
      - 单独模型判断: reference/model.md


theme:
  name: "material"
  palette:
    primary: "red"
    accent: "blue"
  features:
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
          load_external_modules: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: "#"
  - tables
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js